export const contactsApi = "https://mock-api.example.com/patients";

export const contacts = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    age: 45,
    condition: "Hypertension",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/1.jpg",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 32,
    condition: "Diabetes",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/2.jpg",
  },
  {
    id: "3",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 60,
    condition: "Asthma",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/3.jpg",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    age: 28,
    condition: "Allergies",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/4.jpg",
  },
  {
    id: "5",
    name: "David Wilson",
    email: "david.wilson@example.com",
    age: 53,
    condition: "Arthritis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/5.jpg",
  },
  {
    id: "6",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    age: 39,
    condition: "Migraine",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/6.jpg",
  },
  {
    id: "7",
    name: "James Lee",
    email: "james.lee@example.com",
    age: 47,
    condition: "Heart Disease",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/7.jpg",
  },
  {
    id: "8",
    name: "Laura Martinez",
    email: "laura.martinez@example.com",
    age: 25,
    condition: "Anemia",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/8.jpg",
  },
  {
    id: "9",
    name: "Robert Taylor",
    email: "robert.taylor@example.com",
    age: 62,
    condition: "COPD",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/9.jpg",
  },
  {
    id: "10",
    name: "Linda Clark",
    email: "linda.clark@example.com",
    age: 34,
    condition: "Thyroid Disorder",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/10.jpg",
  },
  {
    id: "11",
    name: "Thomas Harris",
    email: "thomas.harris@example.com",
    age: 50,
    condition: "Obesity",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
  },
  {
    id: "12",
    name: "Megan Lewis",
    email: "megan.lewis@example.com",
    age: 29,
    condition: "Depression",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/12.jpg",
  },
  {
    id: "13",
    name: "Charles Walker",
    email: "charles.walker@example.com",
    age: 55,
    condition: "High Cholesterol",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/13.jpg",
  },
  {
    id: "14",
    name: "Amanda Hall",
    email: "amanda.hall@example.com",
    age: 41,
    condition: "Kidney Stones",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/14.jpg",
  },
  {
    id: "15",
    name: "Steven Allen",
    email: "steven.allen@example.com",
    age: 37,
    condition: "Gastritis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/15.jpg",
  },
  {
    id: "16",
    name: "Jessica Young",
    email: "jessica.young@example.com",
    age: 30,
    condition: "Anxiety",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/16.jpg",
  },
  {
    id: "17",
    name: "Daniel King",
    email: "daniel.king@example.com",
    age: 48,
    condition: "Back Pain",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/17.jpg",
  },
  {
    id: "18",
    name: "Rebecca Wright",
    email: "rebecca.wright@example.com",
    age: 26,
    condition: "Eczema",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/18.jpg",
  },
  {
    id: "19",
    name: "Paul Scott",
    email: "paul.scott@example.com",
    age: 58,
    condition: "Stroke Recovery",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/19.jpg",
  },
  {
    id: "20",
    name: "Nancy Green",
    email: "nancy.green@example.com",
    age: 33,
    condition: "Insomnia",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/20.jpg",
  },
  {
    id: "21",
    name: "Mark Evans",
    email: "mark.evans@example.com",
    age: 44,
    condition: "Pneumonia",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/21.jpg",
  },
  {
    id: "22",
    name: "Lisa Adams",
    email: "lisa.adams@example.com",
    age: 31,
    condition: "Sinusitis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/22.jpg",
  },
  {
    id: "23",
    name: "George Baker",
    email: "george.baker@example.com",
    age: 52,
    condition: "Liver Disease",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/23.jpg",
  },
  {
    id: "24",
    name: "Karen Nelson",
    email: "karen.nelson@example.com",
    age: 27,
    condition: "Allergic Rhinitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/24.jpg",
  },
  {
    id: "25",
    name: "Edward Carter",
    email: "edward.carter@example.com",
    age: 59,
    condition: "Osteoporosis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
  },
  {
    id: "26",
    name: "Michelle Turner",
    email: "michelle.turner@example.com",
    age: 40,
    condition: "Ulcer",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/26.jpg",
  },
  {
    id: "27",
    name: "Brian Phillips",
    email: "brian.phillips@example.com",
    age: 46,
    condition: "Hernia",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/27.jpg",
  },
  {
    id: "28",
    name: "Susan Parker",
    email: "susan.parker@example.com",
    age: 35,
    condition: "Fibromyalgia",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/28.jpg",
  },
  {
    id: "29",
    name: "Kevin Edwards",
    email: "kevin.edwards@example.com",
    age: 51,
    condition: "Gout",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/29.jpg",
  },
  {
    id: "30",
    name: "Patricia Collins",
    email: "patricia.collins@example.com",
    age: 38,
    condition: "Endometriosis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/30.jpg",
  },
  {
    id: "31",
    name: "Andrew Morris",
    email: "andrew.morris@example.com",
    age: 54,
    condition: "Parkinson's",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/31.jpg",
  },
  {
    id: "32",
    name: "Deborah Rogers",
    email: "deborah.rogers@example.com",
    age: 29,
    condition: "Psoriasis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/32.jpg",
  },
  {
    id: "33",
    name: "Jason Reed",
    email: "jason.reed@example.com",
    age: 43,
    condition: "Hepatitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/33.jpg",
  },
  {
    id: "34",
    name: "Cynthia Cook",
    email: "cynthia.cook@example.com",
    age: 36,
    condition: "IBS",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/34.jpg",
  },
  {
    id: "35",
    name: "Matthew Morgan",
    email: "matthew.morgan@example.com",
    age: 49,
    condition: "Chronic Fatigue",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/35.jpg",
  },
  {
    id: "36",
    name: "Angela Bailey",
    email: "angela.bailey@example.com",
    age: 32,
    condition: "Hypothyroidism",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/36.jpg",
  },
  {
    id: "37",
    name: "Joshua Cooper",
    email: "joshua.cooper@example.com",
    age: 57,
    condition: "Dementia",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
  },
  {
    id: "38",
    name: "Sharon Rivera",
    email: "sharon.rivera@example.com",
    age: 28,
    condition: "Acne",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/38.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/38.jpg",
  },
  {
    id: "39",
    name: "Larry Barnes",
    email: "larry.barnes@example.com",
    age: 61,
    condition: "Prostate Issues",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/39.jpg",
  },
  {
    id: "40",
    name: "Donna Bell",
    email: "donna.bell@example.com",
    age: 33,
    condition: "PCOS",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/40.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/40.jpg",
  },
  {
    id: "41",
    name: "Gary Howard",
    email: "gary.howard@example.com",
    age: 46,
    condition: "Sciatica",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/41.jpg",
  },
  {
    id: "42",
    name: "Carolyn Brooks",
    email: "carolyn.brooks@example.com",
    age: 30,
    condition: "Bronchitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/42.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/42.jpg",
  },
  {
    id: "43",
    name: "Henry Campbell",
    email: "henry.campbell@example.com",
    age: 55,
    condition: "Glaucoma",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/43.jpg",
  },
  {
    id: "44",
    name: "Diane Diaz",
    email: "diane.diaz@example.com",
    age: 42,
    condition: "Gallstones",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/44.jpg",
  },
  {
    id: "45",
    name: "Patrick Murphy",
    email: "patrick.murphy@example.com",
    age: 39,
    condition: "Tinnitus",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/45.jpg",
  },
  {
    id: "46",
    name: "Katherine Gonzalez",
    email: "katherine.gonzalez@example.com",
    age: 34,
    condition: "Vertigo",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/46.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/46.jpg",
  },
  {
    id: "47",
    name: "Raymond Perry",
    email: "raymond.perry@example.com",
    age: 50,
    condition: "Kidney Disease",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/47.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/47.jpg",
  },
  {
    id: "48",
    name: "Gloria Russell",
    email: "gloria.russell@example.com",
    age: 27,
    condition: "Rosacea",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/48.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/48.jpg",
  },
  {
    id: "49",
    name: "Walter Price",
    email: "walter.price@example.com",
    age: 58,
    condition: "Alzheimer's",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/49.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/49.jpg",
  },
  {
    id: "50",
    name: "Teresa Sanders",
    email: "teresa.sanders@example.com",
    age: 31,
    condition: "Lupus",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/50.jpg",
  },
  {
    id: "51",
    name: "Jerry Myers",
    email: "jerry.myers@example.com",
    age: 47,
    condition: "Carpal Tunnel",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/51.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/51.jpg",
  },
  {
    id: "52",
    name: "Evelyn Henderson",
    email: "evelyn.henderson@example.com",
    age: 35,
    condition: "Celiac Disease",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/52.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/52.jpg",
  },
  {
    id: "53",
    name: "Arthur Foster",
    email: "arthur.foster@example.com",
    age: 53,
    condition: "Pancreatitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/53.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
  },
  {
    id: "54",
    name: "Joyce Ortiz",
    email: "joyce.ortiz@example.com",
    age: 29,
    condition: "Hives",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/54.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/54.jpg",
  },
  {
    id: "55",
    name: "Billy Alexander",
    email: "billy.alexander@example.com",
    age: 56,
    condition: "Epilepsy",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/55.jpg",
  },
  {
    id: "56",
    name: "Marilyn Fox",
    email: "marilyn.fox@example.com",
    age: 26,
    condition: "Shingles",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/56.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/56.jpg",
  },
  {
    id: "57",
    name: "Craig Gray",
    email: "craig.gray@example.com",
    age: 48,
    condition: "Tendonitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/57.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/57.jpg",
  },
  {
    id: "58",
    name: "Beverly Powell",
    email: "beverly.powell@example.com",
    age: 32,
    condition: "Meningitis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/58.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/58.jpg",
  },
  {
    id: "59",
    name: "Jimmy Stewart",
    email: "jimmy.stewart@example.com",
    age: 44,
    condition: "Diverticulitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/59.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/59.jpg",
  },
  {
    id: "60",
    name: "Theresa Morris",
    email: "theresa.morris@example.com",
    age: 30,
    condition: "Scoliosis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/60.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/60.jpg",
  },
  {
    id: "61",
    name: "Bobby Long",
    email: "bobby.long@example.com",
    age: 57,
    condition: "Multiple Sclerosis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/61.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/61.jpg",
  },
  {
    id: "62",
    name: "Lillian Ross",
    email: "lillian.ross@example.com",
    age: 28,
    condition: "Conjunctivitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/62.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/62.jpg",
  },
  {
    id: "63",
    name: "Philip Wood",
    email: "philip.wood@example.com",
    age: 49,
    condition: "Hemorrhoids",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/63.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/63.jpg",
  },
  {
    id: "64",
    name: "Janice Hayes",
    email: "janice.hayes@example.com",
    age: 36,
    condition: "Rheumatoid Arthritis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/64.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/64.jpg",
  },
  {
    id: "65",
    name: "Eugene Coleman",
    email: "eugene.coleman@example.com",
    age: 52,
    condition: "Sleep Apnea",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/65.jpg",
  },
  {
    id: "66",
    name: "Wanda Patterson",
    email: "wanda.patterson@example.com",
    age: 31,
    condition: "Varicose Veins",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/66.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/66.jpg",
  },
  {
    id: "67",
    name: "Ralph Watson",
    email: "ralph.watson@example.com",
    age: 58,
    condition: "Cirrhosis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/67.jpg",
  },
  {
    id: "68",
    name: "Frances Hunter",
    email: "frances.hunter@example.com",
    age: 27,
    condition: "Dermatitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/68.jpg",
  },
  {
    id: "69",
    name: "Wayne Simmons",
    email: "wayne.simmons@example.com",
    age: 45,
    condition: "Chronic Pain",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/69.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/69.jpg",
  },
  {
    id: "70",
    name: "Bonnie Ray",
    email: "bonnie.ray@example.com",
    age: 33,
    condition: "UTI",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/70.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/70.jpg",
  },
  {
    id: "71",
    name: "Norman Bryant",
    email: "norman.bryant@example.com",
    age: 50,
    condition: "Atrial Fibrillation",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/71.jpg",
  },
  {
    id: "72",
    name: "Ruby Murray",
    email: "ruby.murray@example.com",
    age: 29,
    condition: "Gingivitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/72.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/72.jpg",
  },
  {
    id: "73",
    name: "Louis Jenkins",
    email: "louis.jenkins@example.com",
    age: 56,
    condition: "Macular Degeneration",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/73.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/73.jpg",
  },
  {
    id: "74",
    name: "Lois Washington",
    email: "lois.washington@example.com",
    age: 34,
    condition: "Overactive Bladder",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/74.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/74.jpg",
  },
  {
    id: "75",
    name: "Earl Hamilton",
    email: "earl.hamilton@example.com",
    age: 47,
    condition: "Plantar Fasciitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/75.jpg",
  },
  {
    id: "76",
    name: "Tammy Cox",
    email: "tammy.cox@example.com",
    age: 32,
    condition: "Mononucleosis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/76.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/76.jpg",
  },
  {
    id: "77",
    name: "Clarence Kelly",
    email: "clarence.kelly@example.com",
    age: 49,
    condition: "Herniated Disc",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/77.jpg",
  },
  {
    id: "78",
    name: "Irene Price",
    email: "irene.price@example.com",
    age: 28,
    condition: "Strep Throat",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/78.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/78.jpg",
  },
  {
    id: "79",
    name: "Todd Bennett",
    email: "todd.bennett@example.com",
    age: 55,
    condition: "Cataracts",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/79.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/79.jpg",
  },
  {
    id: "80",
    name: "Sara Foster",
    email: "sara.foster@example.com",
    age: 30,
    condition: "Tonsillitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/80.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/80.jpg",
  },
  {
    id: "81",
    name: "Albert Gomez",
    email: "albert.gomez@example.com",
    age: 46,
    condition: "Peripheral Neuropathy",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/81.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/81.jpg",
  },
  {
    id: "82",
    name: "Cheryl Butler",
    email: "cheryl.butler@example.com",
    age: 35,
    condition: "Chlamydia",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/82.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/82.jpg",
  },
  {
    id: "83",
    name: "Roy Ward",
    email: "roy.ward@example.com",
    age: 51,
    condition: "Deep Vein Thrombosis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/83.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/83.jpg",
  },
  {
    id: "84",
    name: "Denise Fisher",
    email: "denise.fisher@example.com",
    age: 29,
    condition: "Otitis Media",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/84.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/84.jpg",
  },
  {
    id: "85",
    name: "Harry Duncan",
    email: "harry.duncan@example.com",
    age: 57,
    condition: "Lyme Disease",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/85.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/85.jpg",
  },
  {
    id: "86",
    name: "Jean Hudson",
    email: "jean.hudson@example.com",
    age: 31,
    condition: "Pleurisy",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/86.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/86.jpg",
  },
  {
    id: "87",
    name: "Joe Hart",
    email: "joe.hart@example.com",
    age: 48,
    condition: "Ankylosing Spondylitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/87.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/87.jpg",
  },
  {
    id: "88",
    name: "Marjorie Weaver",
    email: "marjorie.weaver@example.com",
    age: 34,
    condition: "Gastroenteritis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/88.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/88.jpg",
  },
  {
    id: "89",
    name: "Freddie Stone",
    email: "freddie.stone@example.com",
    age: 50,
    condition: "Barrett's Esophagus",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/89.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/89.jpg",
  },
  {
    id: "90",
    name: "Ellen Knight",
    email: "ellen.knight@example.com",
    age: 27,
    condition: "Impetigo",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/90.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/90.jpg",
  },
  {
    id: "91",
    name: "Carlos Peters",
    email: "carlos.peters@example.com",
    age: 56,
    condition: "Sarcoidosis",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/91.jpg",
  },
  {
    id: "92",
    name: "Heidi Marshall",
    email: "heidi.marshall@example.com",
    age: 32,
    condition: "Mumps",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/92.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/92.jpg",
  },
  {
    id: "93",
    name: "Victor Ford",
    email: "victor.ford@example.com",
    age: 45,
    condition: "Sjogren's Syndrome",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/93.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
  },
  {
    id: "94",
    name: "Lydia Andrews",
    email: "lydia.andrews@example.com",
    age: 33,
    condition: "Chickenpox",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/94.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/94.jpg",
  },
  {
    id: "95",
    name: "Nathan Burns",
    email: "nathan.burns@example.com",
    age: 49,
    condition: "Vasculitis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/95.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/95.jpg",
  },
  {
    id: "96",
    name: "Grace Elliott",
    email: "grace.elliott@example.com",
    age: 28,
    condition: "Measles",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/96.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/96.jpg",
  },
  {
    id: "97",
    name: "Roger Dean",
    email: "roger.dean@example.com",
    age: 54,
    condition: "Polymyalgia Rheumatica",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/97.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/97.jpg",
  },
  {
    id: "98",
    name: "Hazel Harper",
    email: "hazel.harper@example.com",
    age: 30,
    condition: "Rubella",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/98.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/98.jpg",
  },
  {
    id: "99",
    name: "Ethan Wells",
    email: "ethan.wells@example.com",
    age: 47,
    condition: "Myasthenia Gravis",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/99.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/99.jpg",
  },
  {
    id: "100",
    name: "Stella Burke",
    email: "stella.burke@example.com",
    age: 35,
    condition: "Whooping Cough",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/women/10.jpg",
  }
];